# Generated by Django 3.1.2 on 2021-01-23 06:01

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='User',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=255)),
                ('email', models.EmailField(max_length=255)),
                ('ifLogged', models.BooleanField(default=False)),
                ('password', models.CharField(max_length=50)),
                ('token', models.CharField(default='', max_length=500, null=True)),
            ],
        ),
    ]
